"""Common candidate-token interfaces for the five-readout comparison panel."""

from .core import (
    FIVE_READOUT_METHODS,
    LAYER_BOUND_METHODS,
    CandidateReadout,
    CandidateSet,
    CandidateToken,
    LayerMismatchError,
    MissingReadoutInputError,
    OptionalDependencyError,
    ReadoutError,
    ReadoutMethod,
    ReadoutMetrics,
    ReadoutPanelResult,
    ReadoutRecord,
    ReadoutRequest,
    aggregate_metrics,
    aligned_candidate_scores,
    evaluate_record,
    multiclass_log_loss,
    restrict_candidate_scores,
    stable_rank,
    stable_softmax,
    validate_same_layer,
)
from .scorers import (
    JLensReadout,
    LogitLensReadout,
    NextTokenReadout,
    RawResidualProbeReadout,
    ReadoutPanel,
    TextOnlyReadout,
    TextPredictor,
)

__all__ = [
    "FIVE_READOUT_METHODS",
    "LAYER_BOUND_METHODS",
    "CandidateReadout",
    "CandidateSet",
    "CandidateToken",
    "JLensReadout",
    "LayerMismatchError",
    "LogitLensReadout",
    "MissingReadoutInputError",
    "NextTokenReadout",
    "OptionalDependencyError",
    "RawResidualProbeReadout",
    "ReadoutError",
    "ReadoutMethod",
    "ReadoutMetrics",
    "ReadoutPanel",
    "ReadoutPanelResult",
    "ReadoutRecord",
    "ReadoutRequest",
    "TextOnlyReadout",
    "TextPredictor",
    "aggregate_metrics",
    "aligned_candidate_scores",
    "evaluate_record",
    "multiclass_log_loss",
    "restrict_candidate_scores",
    "stable_rank",
    "stable_softmax",
    "validate_same_layer",
]
